## GET ALL PARKINGS
GET http://localhost:3888/parkings

### GET PARKING
GET http://localhost:3888/parkings/5

### UPDATE PARKING
PATCH http://localhost:3888/parkings/5
Content-Type: application/json

{
  "city":"LILLE"
}

### POST PARKING
POST http://localhost:3888/parkings
Content-Type: application/json

{
  "id": 12,
  "name": "tarazesdfdsdsf",
  "type": "sdfORT",
  "city": "FARO"
}

### PUT PARKING
PUT http://localhost:3888/parkings/12
Content-Type: application/json

{
  "id": 1,
  "name": "azee",
  "type": "zaregddhh",
  "city": "setheeeing"
}

### DELETE PARKING
DELETE http://localhost:3888/parkings/12