## GET ALL PARKINGS
GET http://localhost:3888/parkings

### GET PARKING
GET http://localhost:3888/parkings/3

### UPDATE PARKING
PATCH http://localhost:3888/parkings/ok
Content-Type: application/json

{
  "city": "cool"
}

### POST PARKING
POST http://localhost:3888/parkings
Content-Type: application/json

{
  "city":"ok"
}

### PUT PARKING
PUT http://localhost:3888/parkings/3
Content-Type: application/json

{
  "id": 1,
  "name": "azee",
  "type": "ok"
}

### DELETE PARKING
DELETE http://localhost:3888/parkings/ok


# Reservation

### GET RESERVATIONS
GET http://localhost:3888/reservations

### GET RESERVATION
GET http://localhost:3888/reservations/4

### DELETE RESERVATION
DELETE http://localhost:3888/reservations/4

### PUT RESERVATION
PUT http://localhost:3888/reservations/3
Content-Type: application/json

{
  "id": 1,
  "name": "azee",
  "type": "zaregddhh",
  "city": "setheeeing"
}

### UPDATE RESERVATION
PATCH http://localhost:3888/reservations/4
Content-Type: application/json

{
  "city":"Ok"
}

### POST RESERVATION
POST http://localhost:3888/reservations
Content-Type: application/json

{
  "id": 5,
  "parkingId": 5,
  "parking": "Parking 5",
  "type": "sdfORT",
  "city": "lille",
  "clientName": "Eddy",
  "vehicle": "car",
  "licensePlate": "3647ee",
  "checkin":"2021-08-15T21:01:27.457Z",
  "checkout":"2021-08-15T21:02:35.664Z"


}